CREATE TABLE [dbo].[Valores]
(
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Valor] [nvarchar](100) NOT NULL,
	CONSTRAINT [PK_Valores] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON) ON [PRIMARY]
)
GO